pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
     parameters {
        choice(name: 'ACTION', choices: ['', 'apply', 'destroy'], description: 'Create or destroy infrastructure')
    }
    environment {
        AWS_REGION = 'us-east-1'
        AWS_CREDENTIALS = 'aws-creds-dev'
    }
    stages{
        stage('Check Trigger Cause') {
            steps {
                script {
                    def buildCause = currentBuild.rawBuild.getCause(hudson.model.Cause$UpstreamCause)
                    if (buildCause != null) {
                        echo "This job was triggered by an upstream job: ${buildCause.upstreamProject} #${buildCause.upstreamBuild}"
                    } else {
                        echo "This job was triggered manually or by another cause."
                    }
                }
            }
        }
        stage('Check Initial Build or Without Param Action') {
            steps {
                script {
                    if (!params.ACTION) {
                        echo "Initial build detected. No action specified. Stopping further stages."
                        currentBuild.result = 'SUCCESS'
                        error("No action specified. Aborting pipeline.")
                    }
                }
            }
        }
        stage('Initialize and plan Infra') {
            when {
                expression { return params.ACTION == 'apply' || params.ACTION == 'destroy' }
            }
            steps{
                script {
                    try{
                        if(params.ACTION == 'apply'){
                            echo 'Planning to apply infrastructure changes.'
                            withAWS(region: env.AWS_REGION, credentials: env.AWS_CREDENTIALS){
                                sh '''
                                    cd 10-sg
                                    terraform init -reconfigure
                                    terraform plan -out=tfplan
                                '''
                            }
                        }
                        else if(params.ACTION == 'destroy'){
                            echo 'Planning to destory infrastructure changes.'
                            withAWS(region: env.AWS_REGION, credentials: env.AWS_CREDENTIALS){
                                sh '''
                                    cd 10-sg
                                    terraform init -reconfigure
                                    terraform plan -destroy -out=tfplan
                                '''
                            }
                        }
                    }catch(Exception e){
                        echo "An error occurred: ${e.message}"
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
        stage('Create or Destroy') {
            when {
                expression { return params.ACTION == 'apply' || params.ACTION == 'destroy' }
            }
            steps{
                script {
                    try{
                        if(params.ACTION == 'apply'){
                            echo 'apply infrastructure.'
                            withAWS(region: env.AWS_REGION, credentials: env.AWS_CREDENTIALS){
                                sh '''
                                    cd 10-sg
                                    terraform apply -auto-approve tfplan
                                '''
                            }
                        }
                        else if(params.ACTION == 'destroy'){
                            echo 'destroy infrastructure.'
                            withAWS(region: env.AWS_REGION, credentials: env.AWS_CREDENTIALS){
                                sh '''
                                    cd 10-sg
                                    terraform destroy -auto-approve
                                '''
                            }
                        }
                    }catch(Exception e){
                        echo "An error occurred: ${e.message}"
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
        stage('Trigger VPC upstream') {
            when {
                expression { return params.ACTION == 'destroy' }
            }
            steps {
                script {
                    if(params.ACTION == 'destroy'){
                        build job: '10-sg', wait: false, parameters: [
                            string(name: 'ACTION', value: params.ACTION)
                        ]
                    }
                }
            }
        }
    }

    post {
        always {
            ansiColor('xterm') {
                echo 'Cleaning up...'
                deleteDir()
            }
        }
        success {
            ansiColor('xterm') {
                echo 'Pipeline succeeded!'
            }
        }
        failure {
            ansiColor('xterm') {
                echo 'Pipeline failed!'
            }
        }
    }
}